### **Importing necessary packages**

In [5]:
pip install -U scikit-learn

     |████████████████████████████████| 9.1 MB 5.1 MB/s eta 0:00:01
     |████████████████████████████████| 297 kB 7.0 MB/s eta 0:00:01
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
You should consider upgrading via the '/usr/local/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [7]:
import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt
import sklearn
import scipy

### **Numpy Arrays**

In [8]:
data = np.array([
    [3, -1.5, 2, -2.5],
    [0, 4, -0.3, 2.1],
    [1, 3.3, -1.9, -4.3]
])
print(data)

[[ 3.  -1.5  2.  -2.5]
 [ 0.   4.  -0.3  2.1]
 [ 1.   3.3 -1.9 -4.3]]


In [12]:
NpArray1 = np.arange(10) # Similar to the python Range function
print(NpArray1)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
NpArray2 = np.arange(10, 100, 5) # Array with elements from 10 -> 100 with a step of 5
print(NpArray2)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [14]:
NpArray3 = np.linspace(0, 10, 50) # Array of 50 equally spaced numbers between 0 & 10
print(NpArray3)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


### **Data preprocessing using mean removal**

Mean-removal or _Standardization_ is a technique that allows us to scale the data and remove any bias from features. It allows us to place our features on the same scale to allow us to compare them with each other.

The resulting data points all have a `mean = 0` and a `standard-deviation = 1`

In [15]:
from sklearn import preprocessing

In [20]:
# Checking on the characteristics of our `data` array we created earlier.
# axis = 0 means along each column, so 1.3333 corresponds to the mean of [3., 0. ,1.] from the first colum od `data`.

print("Mean: ", data.mean(axis=0))
print("Standard deviation: ", data.std(axis=0))

Mean:  [ 1.33333333  1.93333333 -0.06666667 -1.56666667]
Standard deviation:  [1.24721913 2.44449495 1.60069429 2.69485106]


In [18]:
data_standardize = preprocessing.scale(data)

Notice the mean values below are all ~ 0 and the STD is 1

In [19]:
print("Mean: ", data_standardize.mean(axis=0))
print("Standard deviation: ", data_standardize.std(axis=0))

Mean:  [ 5.55111512e-17 -1.11022302e-16 -7.40148683e-17 -1.48029737e-16]
Standard deviation:  [1. 1. 1. 1.]


### **Data Scaling**